name: CI
env:
  APP_NAME: aigc
'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build On Ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install libopencv-dev protobuf-compiler libprotobuf-dev
          wget https://github.com/Tencent/ncnn/releases/download/20230816/ncnn-20230816-full-source.zip
          unzip -d ncnn-20230816-full-source ncnn-20230816-full-source.zip
          cd ncnn-20230816-full-source && mkdir build && cd build && cmake .. && make && make install
          cp -r ./install ../../ncnn
          cd ../../
          mkdir build
          cd build && cmake -DBUILD_SHARED_LIBS=OFF .. && make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-freebsd
          path: ncnn_gfpgan
          if-no-files-found: error
